---
title: "Unique Values"
output: html_document
date: "2025-06-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(synthesizer)
library(synthpop)
library(dplyr)
```

# Function to generate data with a lot of unique values

```{r}
set.seed(3862836)
n_samples <- 40000

generate_unique_dataset <- function(n) {
  
  #raw values
  
  #age
  age_raw <- c(
    rnorm(n * 0.3, mean = -1.5, sd = 1.2),  
    rnorm(n * 0.4, mean = 0, sd = 1.5),      
    rnorm(n * 0.3, mean = 1.5, sd = 1.2)    
  )[1:n]
  age_raw <- age_raw + runif(n, -0.05, 0.05)
  
  #zip
  zip_raw <- runif(n, -3, 3) + rnorm(n, 0, 0.1)
  
  #gender
  gender_raw <- rnorm(n, 0, 1) + runif(n, -0.02, 0.02)
  
  #education
  edu_raw <- c(
    runif(n * 0.25, -3, -0.8),      #high School
    runif(n * 0.2, -0.8, -0.2),     #some College  
    runif(n * 0.25, -0.2, 0.4),     #bachelor's
    runif(n * 0.2, 0.4, 1),         #master's
    runif(n * 0.1, 1, 3)            #PhD
  )[sample(1:(n * 1.0), n)]  
  edu_raw <- edu_raw + rnorm(n, 0, 0.05)
  
  #ethnicity
  ethn_raw <- c(
    runif(n * 0.3, -3, -0.8),       #white
    runif(n * 0.2, -0.8, -0.2),     #black
    runif(n * 0.2, -0.2, 0.4),      #hispanic
    runif(n * 0.2, 0.4, 1),         #asian
    runif(n * 0.1, 1, 3)            #other
  )[sample(1:(n * 1.0), n)]
  ethn_raw <- ethn_raw + rnorm(n, 0, 0.05)
  
  #marital
  marital_raw <- c(
    runif(n * 0.35, -3, -0.5),      #single
    runif(n * 0.4, -0.5, 0.5),      #married
    runif(n * 0.25, 0.5, 3)         #divorced
  )[sample(1:(n * 1.0), n)]
  marital_raw <- marital_raw + rnorm(n, 0, 0.05)
  
  #job
  job_raw <- c(
    runif(n * 0.15, -3, -0.8),      #unemployed
    runif(n * 0.25, -0.8, -0.2),    #service
    runif(n * 0.3, -0.2, 0.4),      #professional
    runif(n * 0.2, 0.4, 1),         #management
    runif(n * 0.1, 1, 3)            #executive
  )[sample(1:(n * 1.0), n)]
  job_raw <- job_raw + rnorm(n, 0, 0.05)
  
  #income
  income_raw <- c(
    rnorm(n * 0.2, mean = -1.5, sd = 0.8),  #lower incomes
    rnorm(n * 0.3, mean = -0.5, sd = 0.6),  #lower-middle
    rnorm(n * 0.3, mean = 0.5, sd = 0.6),   #ppper-middle  
    rnorm(n * 0.15, mean = 1.5, sd = 0.8),  #higher incomes
    rnorm(n * 0.05, mean = 2.5, sd = 1.0)   #very high incomes
  )[sample(1:(n * 1.0), n)]
  income_raw <- income_raw + runif(n, -0.1, 0.1)  
  
  #transform dataset for specific values for each variable
  dataset <- data.frame(
    age_raw = age_raw,
    zip_raw = zip_raw,
    gender_raw = gender_raw,
    edu_raw = edu_raw,
    ethn_raw = ethn_raw,
    marital_raw = marital_raw,
    job_raw = job_raw,
    income_raw = income_raw
  ) %>%
  mutate(
    age = round(pnorm(age_raw) * 70 + 18),  #age 18-88
    zip_code = round(pnorm(zip_raw) * 89999 + 10000),  #zip 10000-99999
    gender = ifelse(gender_raw > 0, "Male", "Female"), 
    education_level = cut(edu_raw, 
                         breaks = c(-Inf, -0.8, -0.2, 0.4, 1, Inf),
                         labels = c("High School", "Some College", "Bachelor's", "Master's", "PhD")),
    ethnicity = cut(ethn_raw, 
                   breaks = c(-Inf, -0.8, -0.2, 0.4, 1, Inf),
                   labels = c("White", "Black", "Hispanic", "Asian", "Other")),
    marital_status = cut(marital_raw,
                        breaks = c(-Inf, -0.5, 0.5, Inf),
                        labels = c("Single", "Married", "Divorced")),
    job = cut(job_raw,
             breaks = c(-Inf, -0.8, -0.2, 0.4, 1, Inf),
             labels = c("Unemployed", "Service", "Professional", "Management", "Executive")),
    income = round(exp(income_raw + 10.5) / 100) * 100  
  ) %>%
  select(-ends_with("_raw"))
  
  return(dataset)
}
```

# High uniqueness data

```{r}
high_unique <- generate_unique_dataset(n_samples)
```

# Generate synthetic data

```{r}
set.seed(3862836)
train_ind <- sample(1:nrow(high_unique), size = 0.8 * nrow(high_unique))  
train <- high_unique[train_ind, ]
control <- high_unique[-train_ind, ]
```


```{r}
shigh_unique <- synthesize(train)
shigh_unique09 <- synthesize(train, rankcor = 0.9)
synhigh_unique <- syn(train,method = "cart")$syn
```
# Save data

```{r}
write.csv(train,"C:/Users/maria/OneDrive/Υπολογιστής/Thesis/Computational_Study/high_unique/train.csv",row.names = FALSE)
write.csv(control,"C:/Users/maria/OneDrive/Υπολογιστής/Thesis/Computational_Study/high_unique/control.csv",row.names = FALSE)

write.csv(shigh_unique,"C:/Users/maria/OneDrive/Υπολογιστής/Thesis/Computational_Study/high_unique/shigh_unique.csv",row.names = FALSE)
write.csv(shigh_unique09,"C:/Users/maria/OneDrive/Υπολογιστής/Thesis/Computational_Study/high_unique/shigh_unique09.csv",row.names = FALSE)
write.csv(synhigh_unique,"C:/Users/maria/OneDrive/Υπολογιστής/Thesis/Computational_Study/high_unique/synhigh_unique.csv",row.names = FALSE)
```

# Generate synthetic data with synthesizer with different rank correlations

```{r}
synthesize_and_save <- function(train_data, output_dir) {
  for (r in round(seq(1.00, 0.60, by = -0.01), 2)) {
    r_str <- sprintf("%03d", as.integer(r * 100))
    
    synthesized_data <- synthesize(train_data, rankcor = r)
    
    file_name <- paste0("shigh_unique", r_str, ".csv")
    full_path <- file.path(output_dir, file_name)
    
    write.csv(synthesized_data, full_path, row.names = FALSE)
  }
}
```

```{r}
output_path <- "C:/Users/maria/OneDrive/Υπολογιστής/Thesis/Computational_Study/high_unique"
synthesize_and_save(train_data = train, output_dir = output_path)
```

