---
title: "high cor"
output: html_document
date: "2025-04-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mvtnorm)
library(MASS)  
library(dplyr)
library(Matrix)
library(synthesizer)
library(synthpop)

library(corrplot)
library(ggcorrplot)
library(GGally)
library(dplyr)
```

```{r}
set.seed(3862836)

n <- 40000  

cor_matrix2 <- matrix(c(
  # age, zip, gender, edu, ethn, marital, job, income
    1.0,  0.3,   0.1,  0.4,  0.7,    0.8,  0.6,   0.9,  # age
    0.3,  1.0,   0.2,  0.3,  0.9,    0.8,  0.9,   0.7,  # zip
    0.1,  0.2,   1.0,  0.3,  0.6,    0.7,  0.8,   0.8,  # gender
    0.4,  0.3,   0.3,  1.0,  0.9,    0.9,  0.8,   0.8,  # edu
    0.7,  0.9,   0.6,  0.9,  1.0,    0.7,  0.2,   0.5,  # ethn
    0.8,  0.8,   0.7,  0.9,  0.7,    1.0,  0.4,   0.6,  # marital
    0.6,  0.9,   0.8,  0.8,  0.2,    0.4,  1.0,   0.8,  # job
    0.9,  0.7,   0.8,  0.8,  0.5,    0.6,  0.8,   1.0   # income
), nrow = 8, byrow = TRUE)

pd_matrix2 <- as.matrix(nearPD(cor_matrix2, corr = TRUE)$mat)

continuous_data2 <- MASS::mvrnorm(n = n, mu = rep(0, 8), Sigma = pd_matrix2)
colnames(continuous_data2) <- c("age_raw", "zip_raw", "gender_raw", "edu_raw", 
                              "ethn_raw", "marital_raw", "job_raw", "income_raw")

high_cor <- as.data.frame(continuous_data2) %>%
  mutate(
    age = round(pnorm(age_raw) * 70 + 18),  #age 18-88
    zip_code = round(pnorm(zip_raw) * 89999 + 10000),  #zip 10000-99999
    gender = ifelse(gender_raw > 0, "Male", "Female"), 
    education_level = cut(edu_raw, 
                         breaks = c(-Inf, -0.8, -0.2, 0.4, 1, Inf),
                         labels = c("High School", "Some College", "Bachelor's", "Master's", "PhD")),
    
    ethnicity = cut(ethn_raw, 
                   breaks = c(-Inf, -0.8, -0.2, 0.4, 1, Inf),
                   labels = c("White", "Black", "Hispanic", "Asian", "Other")),
    marital_status = cut(marital_raw,
                        breaks = c(-Inf, -0.5, 0.5, Inf),
                        labels = c("Single", "Married", "Divorced")),
    job = cut(job_raw,
             breaks = c(-Inf, -0.8, -0.2, 0.4, 1, Inf),
             labels = c("Unemployed", "Service", "Professional", "Management", "Executive")),
    income = round(exp(income_raw + 10.5) / 100) * 100  
  ) %>%
  select(-ends_with("_raw"))  
```



```{r}
synthesize_and_save <- function(train_data, output_dir) {
  for (r in seq(0.99, 0.70, by = -0.01)) {
    r_str <- sprintf("%03d", as.integer(r * 100))
    
    synthesized_data <- synthesize(train_data, rankcor = r)
    
    file_name <- paste0("shigh_cor", r_str, ".csv")
    full_path <- file.path(output_dir, file_name)
    
    write.csv(synthesized_data, full_path, row.names = FALSE)
  }
}
```

## Splits using function

```{r}
split_synthesize_save <- function(data, seed, output_dir) {
  set.seed(seed)
  
  train_ind <- sample(1:nrow(data), size = 0.8 * nrow(data))
  train <- data[train_ind, ]
  control <- data[-train_ind, ]
  
  shigh_cor <- synthesize(train)
  synhigh_cor <- syn(train)$syn
  
  write.csv(train, file.path(output_dir, "train.csv"), row.names = FALSE)
  write.csv(control, file.path(output_dir, "control.csv"), row.names = FALSE)
  write.csv(shigh_cor, file.path(output_dir, "shigh_cor.csv"), row.names = FALSE)
  write.csv(synhigh_cor, file.path(output_dir, "synhigh_cor.csv"), row.names = FALSE)
  
  synthesize_and_save(train_data = train, output_dir = output_dir)
}

```

## 2nd split

```{r}
split_synthesize_save(high_cor,123,"C:/Users/maria/OneDrive/Υπολογιστής/Thesis/Computational_Study/high_cor/High_Cor2")
```

## 3d split

```{r}
split_synthesize_save(high_cor,12338247,"C:/Users/maria/OneDrive/Υπολογιστής/Thesis/Computational_Study/high_cor/High_Cor3")
```

## 4th split

```{r}
split_synthesize_save(high_cor,123382,"C:/Users/maria/OneDrive/Υπολογιστής/Thesis/Computational_Study/high_cor/High_Cor4")
```

## 5th split

```{r}
split_synthesize_save(high_cor,12338162,"C:/Users/maria/OneDrive/Υπολογιστής/Thesis/Computational_Study/high_cor/High_Cor5")
```


## 6th split

```{r}
split_synthesize_save(high_cor,82319,"C:/Users/maria/OneDrive/Υπολογιστής/Thesis/Computational_Study/high_cor/High_Cor6")
```

## 7th split

```{r}
split_synthesize_save(high_cor,8227319,"C:/Users/maria/OneDrive/Υπολογιστής/Thesis/Computational_Study/high_cor/High_Cor9")
```

## 8th split

```{r}
split_synthesize_save(high_cor,97321,"C:/Users/maria/OneDrive/Υπολογιστής/Thesis/Computational_Study/high_cor/High_Cor/High_Cor9")
```

## 9th split

```{r}
split_synthesize_save(high_cor,3821919,"C:/Users/maria/OneDrive/Υπολογιστής/Thesis/Computational_Study/high_cor/High_Cor9")
```

## 10th split

```{r}
split_synthesize_save(high_cor,6528,"C:/Users/maria/OneDrive/Υπολογιστής/Thesis/Computational_Study/high_cor/High_Cor10")
```



